# Generated by Django 6.0.2 on 2026-03-04 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('health_status', models.CharField(choices=[('excellent', 'عالی'), ('good', 'خوب'), ('normal', 'معمولی'), ('needs_care', 'نیاز به مراقبت')], default='good', max_length=50)),
                ('diagnosis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گزارش صحی',
                'verbose_name_plural': 'گزارشات صحی',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StudentPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('leave', 'مرخصی')], default='present', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'حضوری شاگرد',
                'verbose_name_plural': 'حضوری شاگردان',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('late', 'دیر')], default='present', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حضور داکتر',
                'verbose_name_plural': 'حضور داکتران',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('goal', models.TextField(blank=True)),
                ('material', models.TextField(blank=True)),
                ('activities', models.TextField(blank=True)),
                ('evaluation', models.TextField(blank=True)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.teacher')),
            ],
            options={
                'verbose_name': 'پلان درسی',
                'verbose_name_plural': 'پلان\u200cهای درسی',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غایب'), ('leave', 'مرخصی')], default='present', max_length=20)),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_presence', to='core.teacher')),
            ],
            options={
                'verbose_name': 'حضوری معلم',
                'verbose_name_plural': 'حضوری معلمان',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه')], max_length=20)),
                ('time_slot', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='core.teacher')),
            ],
            options={
                'verbose_name': 'جدول وقت',
                'verbose_name_plural': 'جدول وقت\u200cها',
                'unique_together': {('teacher', 'day', 'time_slot')},
            },
        ),
    ]
