# Generated by Django 6.0.2 on 2026-03-04 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studenthealthreport_studentpresence_doctorpresence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='checkup_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
